apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catalogue.serviceAccountName" . }}
  labels:
    {{- include "catalogue.labels" . | nindent 4 }}

automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
