apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
  labels:
    name: roboshop
    app.kubernetes.io/part-of: roboshop
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: roboshop-quota
  namespace: roboshop
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 12Gi
    limits.cpu: "16"
    limits.memory: 24Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: roboshop-defaults
  namespace: roboshop
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
