apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: roboshop

commonLabels:
  app.kubernetes.io/part-of: roboshop
  app.kubernetes.io/managed-by: kustomize

resources:
  - 00-namespace.yaml
  - 01-config.yaml
  - 10-datastores.yaml
  - 20-microservices.yaml
  - 25-frontend.yaml
  - 30-ingress.yaml
  - 40-hpa-pdb.yaml
  - 50-networkpolicy.yaml

images:
  - name: joindevops/catalogue
    newName: devopman/catalogue
    newTag: 2.0.0

  - name: joindevops/user
    newName: devopman/user
    newTag: 2.0.0

  - name: joindevops/cart
    newName: devopman/cart
    newTag: 2.0.0

  - name: joindevops/shipping
    newName: devopman/shipping
    newTag: 2.0.0

  - name: joindevops/payment
    newName: devopman/payment
    newTag: 2.0.0

  - name: joindevops/frontend
    newName: devopman/frontend
    newTag: 2.0.1

  - name: joindevops/mongodb
    newName: devopman/mongodb
    newTag: 2.0.0

  - name: joindevops/mysql
    newName: devopman/mysql
    newTag: 2.0.0
